export const env = {
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_GA_ID: process.env.NEXT_PUBLIC_GA_ID,
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  NEXT_PUBLIC_VONAGE_API_KEY: process.env.NEXT_PUBLIC_VONAGE_API_KEY,
  NEXT_PUBLIC_VONAGE_API_SECRET: process.env.NEXT_PUBLIC_VONAGE_API_SECRET,
};
