const DEFAULT_PAYWALL_AMOUNT = 13;

export const PAYWALL_AMOUNT_USD = Number(
  process.env.NEXT_PUBLIC_PAYWALL_AMOUNT_USD ??
  process.env.PAYWALL_AMOUNT_USD ??
  DEFAULT_PAYWALL_AMOUNT
) || DEFAULT_PAYWALL_AMOUNT;

export const PAYWALL_CURRENCY = 'USD';
