const DEFAULT_PAYWALL_AMOUNT = 13;

export const PAYWALL_AMOUNT_USD = Number(
  process.env.NEXT_PUBLIC_PAYWALL_AMOUNT_USD ??
  process.env.PAYWALL_AMOUNT_USD ??
  DEFAULT_PAYWALL_AMOUNT
) || DEFAULT_PAYWALL_AMOUNT;

export const PAYWALL_CURRENCY = 'USD';

export const PAYMENT_PROCESSING_TIMEOUT_MINUTES = Number(
  process.env.NEXT_PUBLIC_PAYMENT_PROCESSING_TIMEOUT_MINUTES ??
  process.env.PAYMENT_PROCESSING_TIMEOUT_MINUTES ??
  5
) || 5;

export const PAYMENT_PROCESSING_TIMEOUT_MS = PAYMENT_PROCESSING_TIMEOUT_MINUTES * 60_000;
