import { Notification, AppointmentNotification } from '../../domain/entities/Notification';
import { INotificationRepository } from '../../domain/repositories/INotificationRepository';
import { IAppointmentRepository } from '../../domain/repositories/IAppointmentRepository';

export interface NotificationData {
  userId: string;
  type: 'appointment' | 'payment' | 'system' | 'profile';
  title: string;
  message: string;
  data?: Record<string, any>;
}

export interface CreateNotificationResult {
  notification: Notification;
  success: boolean;
  error?: string;
}

export class CreateNotificationUseCase {
  constructor(
    private readonly notificationRepository: INotificationRepository
  ) {}

  async execute(data: NotificationData): Promise<CreateNotificationResult> {
    try {
      const notification = Notification.create({
        id: '', // Will be generated by repository
        userId: data.userId,
        type: data.type,
        title: data.title,
        message: data.message,
        data: data.data,
        read: false,
        dismissed: false,
        createdAt: new Date().toISOString()
      });

      const createdNotification = await this.notificationRepository.create(notification);

      return {
        notification: createdNotification,
        success: true
      };
    } catch (error) {
      return {
        notification: null as any,
        success: false,
        error: error instanceof Error ? error.message : 'Failed to create notification'
      };
    }
  }

  async createAppointmentNotification(
    userId: string,
    appointmentId: string,
    action: 'created' | 'confirmed' | 'cancelled' | 'completed' | 'payment_required',
    title: string,
    message: string
  ): Promise<CreateNotificationResult> {
    const notificationData: NotificationData = {
      userId,
      type: 'appointment',
      title,
      message,
      data: {
        appointmentId,
        action
      }
    };

    const result = await this.execute(notificationData);
    
    if (result.success) {
      // Convert to AppointmentNotification
      const appointmentNotification = AppointmentNotification.create({
        ...result.notification,
        appointmentId,
        action
      });
      
      return {
        notification: appointmentNotification,
        success: true
      };
    }

    return result;
  }

  async getUserNotifications(userId: string): Promise<Notification[]> {
    return await this.notificationRepository.getUserNotifications(userId);
  }

  async getUnreadNotifications(userId: string): Promise<Notification[]> {
    return await this.notificationRepository.getUnreadNotifications(userId);
  }

  async markAsRead(notificationId: string): Promise<Notification> {
    return await this.notificationRepository.markAsRead(notificationId);
  }

  async markAllAsRead(userId: string): Promise<Notification[]> {
    return await this.notificationRepository.markAllAsRead(userId);
  }

  async dismissNotification(notificationId: string): Promise<Notification> {
    return await this.notificationRepository.dismissNotification(notificationId);
  }

  async dismissAll(userId: string): Promise<Notification[]> {
    return await this.notificationRepository.dismissAll(userId);
  }
}