import { Appointment, AppointmentStatus } from '../../domain/entities/Appointment';
import { IAppointmentRepository } from '../../domain/repositories/IAppointmentRepository';
import { IUserRepository } from '../../domain/repositories/IUserRepository';
import { IAppointmentDomainService } from '../../domain/services/IDomainServices';
import { INotificationRepository } from '../../domain/repositories/INotificationRepository';

export interface CreateAppointmentDTO {
  doctorId: string;
  patientId: string;
  appointmentType: string;
  preferredDate: string;
  preferredTime: string;
  notes: string;
}

export interface CreateAppointmentResult {
  appointment: Appointment;
  success: boolean;
  error?: string;
}

export class CreateAppointmentUseCase {
  constructor(
    private readonly appointmentRepository: IAppointmentRepository,
    private readonly userRepository: IUserRepository,
    private readonly appointmentDomainService: IAppointmentDomainService,
    private readonly notificationRepository: INotificationRepository
  ) {}

  async execute(data: CreateAppointmentDTO): Promise<CreateAppointmentResult> {
    try {
      // Validate users exist
      const doctor = await this.userRepository.getById(data.doctorId);
      const patient = await this.userRepository.getById(data.patientId);
      
      if (!doctor || !patient) {
        return {
          appointment: null as any,
          success: false,
          error: 'Doctor or patient not found'
        };
      }

      // Check if time slot is available
      const isTimeSlotAvailable = await this.appointmentDomainService.isTimeSlotAvailable(
        data.doctorId,
        data.preferredDate,
        data.preferredTime
      );

      if (!isTimeSlotAvailable) {
        return {
          appointment: null as any,
          success: false,
          error: 'Time slot is not available'
        };
      }

      // Create appointment
      const appointment = Appointment.create({
        id: '', // Will be generated by repository
        doctorId: data.doctorId,
        doctorName: `${doctor.profile.firstName} ${doctor.profile.lastName}`,
        patientId: data.patientId,
        patientName: `${patient.profile.firstName} ${patient.profile.lastName}`,
        appointmentType: data.appointmentType,
        preferredDate: data.preferredDate,
        preferredTime: data.preferredTime,
        notes: data.notes,
        isPaid: false,
        createdAt: new Date().toISOString(),
        status: AppointmentStatus.PENDING
      });

      const createdAppointment = await this.appointmentRepository.create(appointment);

      // Process domain logic
      await this.appointmentDomainService.processAppointmentCreation(createdAppointment);

      // Create notification for doctor
      // Note: This would need notification service implementation
      // await this.createNotificationForDoctor(createdAppointment);

      return {
        appointment: createdAppointment,
        success: true
      };
    } catch (error) {
      return {
        appointment: null as any,
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error occurred'
      };
    }
  }
}