import { CurrentUserRepository } from '@/infrastructure/repositories/CurrentUserRepository';
import { FirebaseSessionRepository } from '@/infrastructure/repositories/FirebaseSessionRepository';
import { AuthServiceAdapter } from '@/infrastructure/services/authServiceAdapter';
import { UserProfileService } from '@/infrastructure/services/userProfileService';
import { DoctorProfileService } from '@/infrastructure/services/doctorProfileService';
import { VideoSessionService } from '@/infrastructure/services/videoSessionService';
import { AdminStatsServiceAdapter } from '@/infrastructure/services/adminStatsServiceAdapter';
import { AdminUserService } from '@/infrastructure/services/adminUserService';
import { SessionService } from '@/infrastructure/services/sessionService';
import { RealtimeAppointmentsService } from '@/infrastructure/services/realtimeAppointmentsService';
import { AuthLoginService } from '@/infrastructure/services/authLoginService';
import { RegistrationService } from '@/infrastructure/services/registrationService';
import { DoctorSearchService } from '@/infrastructure/services/doctorSearchService';
import { GA4AnalyticsService } from '@/infrastructure/services/analyticsService';
import { BlogServiceAdapter } from '@/infrastructure/services/blogServiceAdapter';
import { AvailabilityServiceAdapter } from '@/infrastructure/services/availabilityServiceAdapter';
import { AppointmentQueryServiceAdapter } from '@/infrastructure/services/appointmentQueryServiceAdapter';
import { AppointmentBookingServiceAdapter } from '@/infrastructure/services/appointmentBookingServiceAdapter';
import { ClinicBookingServiceAdapter } from '@/infrastructure/services/clinicBookingServiceAdapter';
import { PaymentSyncServiceAdapter } from '@/infrastructure/services/paymentSyncServiceAdapter';
import { ReciepeService } from '@/infrastructure/services/reciepeService';
import { AppointmentPaymentService } from '@/infrastructure/services/appointmentPaymentService';
import { PaymentCheckoutService } from '@/infrastructure/services/paymentCheckoutService';
import { SecurityLogsService } from '@/infrastructure/services/securityLogsService';
import { NotificationService } from '@/infrastructure/services/notificationService';
import { AppointmentService } from '@/infrastructure/services/appointmentService';
import { ClinicBookingRepository } from '@/infrastructure/services/clinicBookingRepository';
import { PharmacyService } from '@/infrastructure/services/pharmacyService';
import { AppointmentNotificationService } from '@/infrastructure/services/appointmentNotificationService';
import { BackendClinicRepository } from '@/infrastructure/services/backendClinicRepository';
import { UserNotificationsService } from '@/infrastructure/services/userNotificationsService';
import type { IUserNotificationsService } from '@/application/ports/IUserNotificationsService';
import { HandlePayNowUseCase } from '@/application/handlePayNowUseCase';
import { GenerateRoomCodeUseCase } from '@/application/generateRoomCodeUseCase';
import { GetTopDoctorsByAppointmentsUseCase } from '@/application/getTopDoctorsByAppointmentsUseCase';
import { GetTopDoctorsByRequestsUseCase } from '@/application/getTopDoctorsByRequestsUseCase';
import { LogoutServerUseCase } from '@/application/logoutServerUseCase';
import { LogoutSessionUseCase } from '@/application/logoutSessionUseCase';
import { SubscribePendingNotificationsUseCase } from '@/application/subscribePendingNotificationsUseCase';
import { LoginUseCase } from '@/application/loginUseCase';
import { TestAuthConnectionUseCase } from '@/application/testAuthConnectionUseCase';
import { RegisterUserUseCase } from '@/application/registerUserUseCase';
import { FetchDoctorsUseCase } from '@/application/fetchDoctorsUseCase';
import { GetSpecializationsUseCase } from '@/application/getSpecializationsUseCase';
import { GetUserProfileUseCase } from '@/application/getUserProfileUseCase';
import { UpdateUserProfileUseCase } from '@/application/updateUserProfileUseCase';
import { UploadProfilePictureUseCase } from '@/application/uploadProfilePictureUseCase';
import { ResetUserPasswordUseCase } from '@/application/resetUserPasswordUseCase';
import { GetDoctorProfileUseCase } from '@/application/getDoctorProfileUseCase';
import { CheckProfileCompleteUseCase } from '@/application/checkProfileCompleteUseCase';
import { CreateReciepeUseCase } from '@/application/createReciepeUseCase';
import { GetReciepesByDoctorUseCase } from '@/application/getReciepesByDoctorUseCase';
import { GetReciepesByPatientUseCase } from '@/application/getReciepesByPatientUseCase';
import { GetReciepesByPharmacyUseCase } from '@/application/getReciepesByPharmacyUseCase';
import { UpdateReciepeStatusUseCase } from '@/application/updateReciepeStatusUseCase';
import { GetAvailabilityUseCase } from '@/application/getAvailabilityUseCase';
import { GetAvailabilityPresetsUseCase } from '@/application/getAvailabilityPresetsUseCase';
import { SaveAvailabilityUseCase } from '@/application/saveAvailabilityUseCase';
import { GetResolvedSlotsUseCase } from '@/application/getResolvedSlotsUseCase';
import { GetIdTokenUseCase } from '@/application/getIdTokenUseCase';
import { ReauthenticateUseCase } from '@/application/reauthenticateUseCase';
import { SendVerificationEmailUseCase } from '@/application/sendVerificationEmailUseCase';
import { EstablishSessionUseCase } from '@/application/establishSessionUseCase';
import { ReloadUserUseCase } from '@/application/reloadUserUseCase';
import { GetUsersByRoleUseCase } from '@/application/getUsersByRoleUseCase';
import { ApplyVerificationCodeUseCase } from '@/application/applyVerificationCodeUseCase';
import { EstablishSessionAllowUnverifiedUseCase } from '@/application/establishSessionAllowUnverifiedUseCase';
import { PrepareCheckoutUseCase } from '@/application/prepareCheckoutUseCase';
import { OpenCheckoutUseCase } from '@/application/openCheckoutUseCase';
import { SyncPaymentUseCase } from '@/application/syncPaymentUseCase';
import { ClearPaymentProcessingUseCase } from '@/application/clearPaymentProcessingUseCase';
import { ListAppointmentsUseCase } from '@/application/listAppointmentsUseCase';
import { CreateAppointmentUseCase } from '@/application/createAppointmentUseCase';
import { QuickMatchDoctorUseCase } from '@/application/quickMatchDoctorUseCase';
import { GetAdminDashboardStatsUseCase } from '@/application/getAdminDashboardStatsUseCase';
import { GetSecurityLogsUseCase } from '@/application/getSecurityLogsUseCase';
import { DismissNotificationByIdUseCase } from '@/application/dismissNotificationByIdUseCase';
import { GetClinicsUseCase } from '@/application/getClinicsUseCase';
import { GetClinicBookingsUseCase } from '@/application/getClinicBookingsUseCase';
import { CreateClinicBookingUseCase } from '@/application/createClinicBookingUseCase';
import { UpdateClinicBookingStatusUseCase } from '@/application/updateClinicBookingStatusUseCase';
import { DismissNotificationUseCase } from '@/application/dismissNotificationUseCase';
import { UpdateAppointmentStatusAndNotifyUseCase } from '@/application/updateAppointmentStatusAndNotifyUseCase';
import { GetPharmaciesUseCase } from '@/application/getPharmaciesUseCase';
import { GetQuickAppointmentMatchesUseCase } from '@/application/getQuickAppointmentMatchesUseCase';
import { QuickAppointmentService } from '@/infrastructure/services/quickAppointmentService';
import type { IQuickAppointmentService } from '@/application/ports/IQuickAppointmentService';
import { ListUserNotificationsUseCase } from '@/application/listUserNotificationsUseCase';
import { MarkUserNotificationReadUseCase } from '@/application/markUserNotificationReadUseCase';
import { MarkAllUserNotificationsReadUseCase } from '@/application/markAllUserNotificationsReadUseCase';
import { RequestUserNotificationsExportUseCase } from '@/application/requestUserNotificationsExportUseCase';
import type { IAnalyticsService } from '@/application/ports/IAnalyticsService';
import type { IAuthService } from '@/application/ports/IAuthService';
import type { IPaymentCheckoutService } from '@/application/ports/IPaymentCheckoutService';
import type { IBlogService } from '@/application/ports/IBlogService';
import type { IAvailabilityService } from '@/application/ports/IAvailabilityService';
import type { IAdminUserService } from '@/application/ports/IAdminUserService';
import type { IAdminStatsService } from '@/application/ports/IAdminStatsService';
import type { IAppointmentQueryService } from '@/application/ports/IAppointmentQueryService';
import type { IAppointmentBookingService } from '@/application/ports/IAppointmentBookingService';
import type { IClinicBookingService } from '@/application/ports/IClinicBookingService';
import type { IPaymentSyncService } from '@/application/ports/IPaymentSyncService';

export const userRepo = new CurrentUserRepository();
export const sessionRepo = new FirebaseSessionRepository();
export const authService: IAuthService = new AuthServiceAdapter();
export const userProfileService = new UserProfileService();
export const doctorProfileService = new DoctorProfileService();
export const videoSessionService = new VideoSessionService();
export const adminStatsService: IAdminStatsService = new AdminStatsServiceAdapter();
export const adminUserService: IAdminUserService = new AdminUserService();
export const sessionService = new SessionService();
export const realtimeAppointmentsService = new RealtimeAppointmentsService();
export const authLoginService = new AuthLoginService();
export const registrationService = new RegistrationService();
export const doctorSearchService = new DoctorSearchService();
export const analyticsService: IAnalyticsService = new GA4AnalyticsService();
export const reciepeService = new ReciepeService();
export const appointmentPaymentService = new AppointmentPaymentService();
export const paymentCheckoutService: IPaymentCheckoutService = new PaymentCheckoutService();
export const blogService: IBlogService = new BlogServiceAdapter();
export const availabilityService: IAvailabilityService = new AvailabilityServiceAdapter();
export const appointmentQueryService: IAppointmentQueryService = new AppointmentQueryServiceAdapter();
export const appointmentBookingService: IAppointmentBookingService = new AppointmentBookingServiceAdapter();
export const clinicBookingService: IClinicBookingService = new ClinicBookingServiceAdapter();
export const paymentSyncService: IPaymentSyncService = new PaymentSyncServiceAdapter();
export const securityLogsService = new SecurityLogsService();
export const notificationService = new NotificationService();
export const appointmentService = new AppointmentService();
export const clinicRepository = new BackendClinicRepository();
export const clinicBookingRepository = new ClinicBookingRepository();
export const pharmacyService = new PharmacyService();
export const appointmentNotificationService = new AppointmentNotificationService();
export const userNotificationsService: IUserNotificationsService = new UserNotificationsService();

export const handlePayNowUseCase = new HandlePayNowUseCase(appointmentPaymentService, paymentCheckoutService);
export const generateRoomCodeUseCase = new GenerateRoomCodeUseCase(videoSessionService, analyticsService);
export const getTopDoctorsByAppointmentsUseCase = new GetTopDoctorsByAppointmentsUseCase(adminStatsService);
export const getTopDoctorsByRequestsUseCase = new GetTopDoctorsByRequestsUseCase(adminStatsService);
export const logoutServerUseCase = new LogoutServerUseCase(sessionService);
export const logoutSessionUseCase = new LogoutSessionUseCase(sessionRepo);
export const subscribePendingNotificationsUseCase = new SubscribePendingNotificationsUseCase(realtimeAppointmentsService);
export const loginUseCase = new LoginUseCase(authLoginService, analyticsService);
export const testAuthConnectionUseCase = new TestAuthConnectionUseCase(authLoginService);
export const registerUserUseCase = new RegisterUserUseCase(registrationService, analyticsService);
export const fetchDoctorsUseCase = new FetchDoctorsUseCase(doctorSearchService);
export const getSpecializationsUseCase = new GetSpecializationsUseCase(doctorSearchService);
export const listUserNotificationsUseCase = new ListUserNotificationsUseCase(userNotificationsService);
export const markUserNotificationReadUseCase = new MarkUserNotificationReadUseCase(userNotificationsService);
export const markAllUserNotificationsReadUseCase = new MarkAllUserNotificationsReadUseCase(userNotificationsService);
export const requestUserNotificationsExportUseCase = new RequestUserNotificationsExportUseCase(userNotificationsService);
export const getUserProfileUseCase = new GetUserProfileUseCase(userProfileService);
export const updateUserProfileUseCase = new UpdateUserProfileUseCase(userProfileService, authService);
export const uploadProfilePictureUseCase = new UploadProfilePictureUseCase(userProfileService);
export const resetUserPasswordUseCase = new ResetUserPasswordUseCase(authService);
export const getDoctorProfileUseCase = new GetDoctorProfileUseCase(doctorProfileService);
export const checkProfileCompleteUseCase = new CheckProfileCompleteUseCase(userRepo);
export const createReciepeUseCase = new CreateReciepeUseCase(reciepeService, analyticsService);
export const getReciepesByDoctorUseCase = new GetReciepesByDoctorUseCase(reciepeService);
export const getReciepesByPatientUseCase = new GetReciepesByPatientUseCase(reciepeService);
export const getReciepesByPharmacyUseCase = new GetReciepesByPharmacyUseCase(reciepeService);
export const updateReciepeStatusUseCase = new UpdateReciepeStatusUseCase(reciepeService);
export const getAvailabilityUseCase = new GetAvailabilityUseCase(availabilityService);
export const getAvailabilityPresetsUseCase = new GetAvailabilityPresetsUseCase(availabilityService);
export const saveAvailabilityUseCase = new SaveAvailabilityUseCase(availabilityService);
export const getResolvedSlotsUseCase = new GetResolvedSlotsUseCase(availabilityService);
export const getIdTokenUseCase = new GetIdTokenUseCase(authService);
export const reauthenticateUseCase = new ReauthenticateUseCase(authService);
export const sendVerificationEmailUseCase = new SendVerificationEmailUseCase(authService);
export const establishSessionUseCase = new EstablishSessionUseCase(authService);
export const reloadUserUseCase = new ReloadUserUseCase(authService);
export const getUsersByRoleUseCase = new GetUsersByRoleUseCase(adminUserService);
export const applyVerificationCodeUseCase = new ApplyVerificationCodeUseCase(authService);
export const establishSessionAllowUnverifiedUseCase = new EstablishSessionAllowUnverifiedUseCase(authService);
export const prepareCheckoutUseCase = new PrepareCheckoutUseCase(paymentCheckoutService);
export const openCheckoutUseCase = new OpenCheckoutUseCase(paymentCheckoutService);
export const syncPaymentUseCase = new SyncPaymentUseCase(appointmentPaymentService);
export const clearPaymentProcessingUseCase = new ClearPaymentProcessingUseCase(appointmentPaymentService);
export const listAppointmentsUseCase = new ListAppointmentsUseCase(appointmentService);
export const createAppointmentUseCase = new CreateAppointmentUseCase(appointmentService);
export const quickMatchDoctorUseCase = new QuickMatchDoctorUseCase(doctorSearchService, availabilityService);
export const getAdminDashboardStatsUseCase = new GetAdminDashboardStatsUseCase(adminStatsService);
export const getSecurityLogsUseCase = new GetSecurityLogsUseCase(securityLogsService);
export const dismissNotificationByIdUseCase = new DismissNotificationByIdUseCase(notificationService);
export const getClinicsUseCase = new GetClinicsUseCase(clinicRepository);
export const getClinicBookingsUseCase = new GetClinicBookingsUseCase(clinicBookingRepository);
export const createClinicBookingUseCase = new CreateClinicBookingUseCase(clinicBookingRepository);
export const updateClinicBookingStatusUseCase = new UpdateClinicBookingStatusUseCase(clinicBookingRepository);
export const dismissNotificationUseCase = new DismissNotificationUseCase(notificationService);
export const updateAppointmentStatusAndNotifyUseCase = new UpdateAppointmentStatusAndNotifyUseCase(appointmentNotificationService);
export const getPharmaciesUseCase = new GetPharmaciesUseCase(pharmacyService);
export const quickAppointmentService: IQuickAppointmentService = new QuickAppointmentService();
export const getQuickAppointmentMatchesUseCase = new GetQuickAppointmentMatchesUseCase(quickAppointmentService);
