import { CurrentUserRepository } from '@/infrastructure/repositories/CurrentUserRepository';
import { FirebaseSessionRepository } from '@/infrastructure/repositories/FirebaseSessionRepository';
import { AuthServiceAdapter } from '@/infrastructure/services/authServiceAdapter';
import { UserProfileService } from '@/infrastructure/services/userProfileService';
import { DoctorProfileService } from '@/infrastructure/services/doctorProfileService';
import { VideoSessionService } from '@/infrastructure/services/videoSessionService';
import { AdminStatsServiceAdapter } from '@/infrastructure/services/adminStatsServiceAdapter';
import { AdminUserService } from '@/infrastructure/services/adminUserService';
import { SessionService } from '@/infrastructure/services/sessionService';
import { RealtimeAppointmentsService } from '@/infrastructure/services/realtimeAppointmentsService';
import { AuthLoginService } from '@/infrastructure/services/authLoginService';
import { RegistrationService } from '@/infrastructure/services/registrationService';
import { DoctorSearchService } from '@/infrastructure/services/doctorSearchService';
import { GA4AnalyticsService } from '@/infrastructure/services/analyticsService';
import { BlogServiceAdapter } from '@/infrastructure/services/blogServiceAdapter';
import { AvailabilityServiceAdapter } from '@/infrastructure/services/availabilityServiceAdapter';
import { AppointmentQueryServiceAdapter } from '@/infrastructure/services/appointmentQueryServiceAdapter';
import { AppointmentBookingServiceAdapter } from '@/infrastructure/services/appointmentBookingServiceAdapter';
import { ClinicBookingServiceAdapter } from '@/infrastructure/services/clinicBookingServiceAdapter';
import { PaymentSyncServiceAdapter } from '@/infrastructure/services/paymentSyncServiceAdapter';
import { ReciepeService } from '@/infrastructure/services/reciepeService';
import { AppointmentPaymentService } from '@/infrastructure/services/appointmentPaymentService';
import { PaymentCheckoutService } from '@/infrastructure/services/paymentCheckoutService';
import { SecurityLogsService } from '@/infrastructure/services/securityLogsService';
import { NotificationService } from '@/infrastructure/services/notificationService';
import { AppointmentService } from '@/infrastructure/services/appointmentService';
import { ClinicBookingRepository } from '@/infrastructure/services/clinicBookingRepository';
import { PharmacyService } from '@/infrastructure/services/pharmacyService';
import { AppointmentNotificationService } from '@/infrastructure/services/appointmentNotificationService';
import { BackendClinicRepository } from '@/infrastructure/services/backendClinicRepository';
import type { IAnalyticsService } from '@/application/ports/IAnalyticsService';
import type { IAuthService } from '@/application/ports/IAuthService';
import type { IPaymentCheckoutService } from '@/application/ports/IPaymentCheckoutService';
import type { IBlogService } from '@/application/ports/IBlogService';
import type { IAvailabilityService } from '@/application/ports/IAvailabilityService';
import type { IAdminUserService } from '@/application/ports/IAdminUserService';
import type { IAdminStatsService } from '@/application/ports/IAdminStatsService';
import type { IAppointmentQueryService } from '@/application/ports/IAppointmentQueryService';
import type { IAppointmentBookingService } from '@/application/ports/IAppointmentBookingService';
import type { IClinicBookingService } from '@/application/ports/IClinicBookingService';
import type { IPaymentSyncService } from '@/application/ports/IPaymentSyncService';

export const userRepo = new CurrentUserRepository();
export const sessionRepo = new FirebaseSessionRepository();
export const authService: IAuthService = new AuthServiceAdapter();
export const userProfileService = new UserProfileService();
export const doctorProfileService = new DoctorProfileService();
export const videoSessionService = new VideoSessionService();
export const adminStatsService: IAdminStatsService = new AdminStatsServiceAdapter();
export const adminUserService: IAdminUserService = new AdminUserService();
export const sessionService = new SessionService();
export const realtimeAppointmentsService = new RealtimeAppointmentsService();
export const authLoginService = new AuthLoginService();
export const registrationService = new RegistrationService();
export const doctorSearchService = new DoctorSearchService();
export const analyticsService: IAnalyticsService = new GA4AnalyticsService();
export const reciepeService = new ReciepeService();
export const appointmentPaymentService = new AppointmentPaymentService();
export const paymentCheckoutService: IPaymentCheckoutService = new PaymentCheckoutService();
export const blogService: IBlogService = new BlogServiceAdapter();
export const availabilityService: IAvailabilityService = new AvailabilityServiceAdapter();
export const appointmentQueryService: IAppointmentQueryService = new AppointmentQueryServiceAdapter();
export const appointmentBookingService: IAppointmentBookingService = new AppointmentBookingServiceAdapter();
export const clinicBookingService: IClinicBookingService = new ClinicBookingServiceAdapter();
export const paymentSyncService: IPaymentSyncService = new PaymentSyncServiceAdapter();
export const securityLogsService = new SecurityLogsService();
export const notificationService = new NotificationService();
export const appointmentService = new AppointmentService();
export const clinicRepository = new BackendClinicRepository();
export const clinicBookingRepository = new ClinicBookingRepository();
export const pharmacyService = new PharmacyService();
export const appointmentNotificationService = new AppointmentNotificationService();
